/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShareRouteImport } from './routes/share'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsNewRouteImport } from './routes/trips.new'
import { Route as TripsTripIdRouteImport } from './routes/trips.$tripId'
import { Route as TripsTripIdPrintRouteImport } from './routes/trips.$tripId.print'
import { Route as TripsTripIdChecklistRouteImport } from './routes/trips.$tripId.checklist'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsNewRoute = TripsNewRouteImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdRoute = TripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdPrintRoute = TripsTripIdPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => TripsTripIdRoute,
} as any)
const TripsTripIdChecklistRoute = TripsTripIdChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => TripsTripIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/share': typeof ShareRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trips/$tripId': typeof TripsTripIdRouteWithChildren
  '/trips/new': typeof TripsNewRoute
  '/trips/$tripId/checklist': typeof TripsTripIdChecklistRoute
  '/trips/$tripId/print': typeof TripsTripIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/share': typeof ShareRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trips/$tripId': typeof TripsTripIdRouteWithChildren
  '/trips/new': typeof TripsNewRoute
  '/trips/$tripId/checklist': typeof TripsTripIdChecklistRoute
  '/trips/$tripId/print': typeof TripsTripIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/share': typeof ShareRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trips/$tripId': typeof TripsTripIdRouteWithChildren
  '/trips/new': typeof TripsNewRoute
  '/trips/$tripId/checklist': typeof TripsTripIdChecklistRoute
  '/trips/$tripId/print': typeof TripsTripIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/share'
    | '/sitemap.xml'
    | '/trips/$tripId'
    | '/trips/new'
    | '/trips/$tripId/checklist'
    | '/trips/$tripId/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/share'
    | '/sitemap.xml'
    | '/trips/$tripId'
    | '/trips/new'
    | '/trips/$tripId/checklist'
    | '/trips/$tripId/print'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/share'
    | '/sitemap.xml'
    | '/trips/$tripId'
    | '/trips/new'
    | '/trips/$tripId/checklist'
    | '/trips/$tripId/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  ShareRoute: typeof ShareRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TripsTripIdRoute: typeof TripsTripIdRouteWithChildren
  TripsNewRoute: typeof TripsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/new': {
      id: '/trips/new'
      path: '/trips/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof TripsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId': {
      id: '/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof TripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId/print': {
      id: '/trips/$tripId/print'
      path: '/print'
      fullPath: '/trips/$tripId/print'
      preLoaderRoute: typeof TripsTripIdPrintRouteImport
      parentRoute: typeof TripsTripIdRoute
    }
    '/trips/$tripId/checklist': {
      id: '/trips/$tripId/checklist'
      path: '/checklist'
      fullPath: '/trips/$tripId/checklist'
      preLoaderRoute: typeof TripsTripIdChecklistRouteImport
      parentRoute: typeof TripsTripIdRoute
    }
  }
}

interface TripsTripIdRouteChildren {
  TripsTripIdChecklistRoute: typeof TripsTripIdChecklistRoute
  TripsTripIdPrintRoute: typeof TripsTripIdPrintRoute
}

const TripsTripIdRouteChildren: TripsTripIdRouteChildren = {
  TripsTripIdChecklistRoute: TripsTripIdChecklistRoute,
  TripsTripIdPrintRoute: TripsTripIdPrintRoute,
}

const TripsTripIdRouteWithChildren = TripsTripIdRoute._addFileChildren(
  TripsTripIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  ShareRoute: ShareRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TripsTripIdRoute: TripsTripIdRouteWithChildren,
  TripsNewRoute: TripsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
