/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsNewRouteImport } from './routes/trips.new'
import { Route as TripsTripIdRouteImport } from './routes/trips.$tripId'
import { Route as TripsTripIdPrintRouteImport } from './routes/trips.$tripId.print'
import { Route as TripsTripIdChecklistRouteImport } from './routes/trips.$tripId.checklist'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsNewRoute = TripsNewRouteImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdRoute = TripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdPrintRoute = TripsTripIdPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => TripsTripIdRoute,
} as any)
const TripsTripIdChecklistRoute = TripsTripIdChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => TripsTripIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trips/$tripId': typeof TripsTripIdRouteWithChildren
  '/trips/new': typeof TripsNewRoute
  '/trips/$tripId/checklist': typeof TripsTripIdChecklistRoute
  '/trips/$tripId/print': typeof TripsTripIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trips/$tripId': typeof TripsTripIdRouteWithChildren
  '/trips/new': typeof TripsNewRoute
  '/trips/$tripId/checklist': typeof TripsTripIdChecklistRoute
  '/trips/$tripId/print': typeof TripsTripIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trips/$tripId': typeof TripsTripIdRouteWithChildren
  '/trips/new': typeof TripsNewRoute
  '/trips/$tripId/checklist': typeof TripsTripIdChecklistRoute
  '/trips/$tripId/print': typeof TripsTripIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/trips/$tripId'
    | '/trips/new'
    | '/trips/$tripId/checklist'
    | '/trips/$tripId/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/trips/$tripId'
    | '/trips/new'
    | '/trips/$tripId/checklist'
    | '/trips/$tripId/print'
  id:
    | '__root__'
    | '/'
    | '/trips/$tripId'
    | '/trips/new'
    | '/trips/$tripId/checklist'
    | '/trips/$tripId/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TripsTripIdRoute: typeof TripsTripIdRouteWithChildren
  TripsNewRoute: typeof TripsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/new': {
      id: '/trips/new'
      path: '/trips/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof TripsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId': {
      id: '/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof TripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId/print': {
      id: '/trips/$tripId/print'
      path: '/print'
      fullPath: '/trips/$tripId/print'
      preLoaderRoute: typeof TripsTripIdPrintRouteImport
      parentRoute: typeof TripsTripIdRoute
    }
    '/trips/$tripId/checklist': {
      id: '/trips/$tripId/checklist'
      path: '/checklist'
      fullPath: '/trips/$tripId/checklist'
      preLoaderRoute: typeof TripsTripIdChecklistRouteImport
      parentRoute: typeof TripsTripIdRoute
    }
  }
}

interface TripsTripIdRouteChildren {
  TripsTripIdChecklistRoute: typeof TripsTripIdChecklistRoute
  TripsTripIdPrintRoute: typeof TripsTripIdPrintRoute
}

const TripsTripIdRouteChildren: TripsTripIdRouteChildren = {
  TripsTripIdChecklistRoute: TripsTripIdChecklistRoute,
  TripsTripIdPrintRoute: TripsTripIdPrintRoute,
}

const TripsTripIdRouteWithChildren = TripsTripIdRoute._addFileChildren(
  TripsTripIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TripsTripIdRoute: TripsTripIdRouteWithChildren,
  TripsNewRoute: TripsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
